### ISSUE TITLE
Incorrect bytes in data section

### ISSUE THREAD

**Issue by enderdrag64** [yetmorecode/ghidra-lx-loader#1]
Hi! I've been working on a reversing project for a little while on an executable file that I used the lx loader to analyze. I noticed a bit of an issue where it seems like there are several bytes that are messed up in ghidra. Specifically I've noticed the issue in four different instances in the data section of the executable, although it's feasible that its affected the disassembly too.
Here's the issue in action:
![image](https://user-images.githubusercontent.com/33301226/137937730-45462a4c-ade4-4254-a34b-b16c52616741.png)
As you can see, the highlighted byte is a 0x00 where it seemingly should be a 0x17. I can manually override it to be a 0x17 and it accesses the proper address:
![image](https://user-images.githubusercontent.com/33301226/137938219-f35df19d-4c06-4e0f-91a1-052f8b531680.png)

Here's a comparison with the same bytes in a hex editor (I know the addresses appear different but I think that has to do with how they're imported in the disassembler):
![image](https://user-images.githubusercontent.com/33301226/137939733-2a71a766-8ba7-4725-8e9f-adbffd4fa62b.png)
Interestingly, none of them in the hex editor are 0x17

And here's the same bytes in Ida:
![image](https://user-images.githubusercontent.com/33301226/137940329-d392aaf6-e704-4df5-ab19-28cf2c9026d0.png)

More details:
I'm analyzing the RGFX.exe executable from The Elder Scrolls Adventures Redguard.
I'm running Ghidra 10.0.1 with the latest release of the lx loader.

These are the four addresses where I've noticed the issue so far:

0x001a2001 : should be 0x17 but is 0x00

0x001a4001 : should be 0x17 but is 0x00

0x001a2fff : should be 0x17 but is 0x00

0x001a5fff : should be 0x18 but is 0x01

**Comment by enderdrag64** [comment]
Update: The problem is much worse than I initially described. I decided to do a comparison between the imported bytes between ghidra and ida and there's a ton of bytes that are messed up, in both the code and data sections. Many of them fall into the pattern I already described where the byte is 0x17 less than it should be, but I found another type of issue where sometimes the 3 bytes after a call instruction are imported as 00 00 00 instead:
![image](https://user-images.githubusercontent.com/33301226/138367551-a68959f2-1173-4f06-a023-da505a9d3eb9.png)

before manual patch:
![image](https://user-images.githubusercontent.com/33301226/138367611-cbd85b3e-1038-4680-aef8-3404413e23a3.png)

after manual patch:
![image](https://user-images.githubusercontent.com/33301226/138367774-853a6e5d-6eff-41b3-8c4d-b80a8bdcbf99.png)

**Comment by yetmorecode** [comment]
Hey, Thanks for taking the time to write that all up. Much appreciated. I will give it a look.

As far as I'm aware, certain fixups on page boundaries are not implemented correctly. Further, I remember running into issues regarding type conversion between signed and unsigned data in the fixups.

**Comment by yetmorecode** [comment]
Ok, as for your first comment, this is indeed a page boundary fixup issue.

> Interestingly, none of them in the hex editor are 0x17
> 
That's because the compiler will leave references from .code to .data and vice versa blank (null). Only the DOS extender (or Ghidra loader) will known where .code and .data are actually mapped into memory. The exe also has a list of fixups which describe things like ".code at offset Y references .data at offset X". Those offset will be applied to the actual memory positions of .code and .data after they are loaded into memory (i.e. unknown to the exe itself), a the refences in the end "fixed up".

Since .code and .data in LE are divided in chunks of pages, sometimes a fixup will be on the edge of two pages. That's the edge case the loader fails to handle here. 

> These are the four addresses where I've noticed the issue so far:
> 
> 0x001a2001 : should be 0x17 but is 0x00
> 
> 0x001a4001 : should be 0x17 but is 0x00
> 
> 0x001a2fff : should be 0x17 but is 0x00
> 
> 0x001a5fff : should be 0x18 but is 0x01

Not that it would help you without a patch, but you can see those are indeed references on page boundaries.

I will try to fix that.

**Comment by yetmorecode** [comment]
@enderdrag64 I pushed a new realease. Please let me know if there are still unhandled fixups in your file.

**Comment by enderdrag64** [comment]
@yetmorecode Yep I just compared the exported bytes from the old and the new extensions and all the bytes that were 0x17 off are now fixed.

The 3 bytes after some call instructions sometimes being 00 00 00 is unchanged

**Comment by yetmorecode** [comment]
@enderdrag64 Ok, I got a copy of that game and was able to identify the missing fixup types in there. There is a new release, which does not report any unhandled fixups for RGFX.exe anymore for me.

If you turn "Log 32 bit self-refs" on in the options, it will log all those locations.

**Comment by enderdrag64** [comment]
@yetmorecode Okay cool thanks! I tried loading it up with the new release and all the incorrect bytes that I had noticed previously are gone. I did notice a new problem though:
![image](https://user-images.githubusercontent.com/33301226/145101960-a5fd7400-b1c5-4fa9-8169-422d40c801fb.png)
On the left is the latest release and on the right is with the original 10.0.1 release.

I'm not entirely sure which one is correct as both generate seemingly garbage code in the disassembly:
![image](https://user-images.githubusercontent.com/33301226/145102258-0cdcf42b-69b8-42e3-99fc-af9e8bca7ab1.png)
![image](https://user-images.githubusercontent.com/33301226/145102306-10397c9f-10e6-470b-9965-13a10a25317c.png)

Ida pro imports it with both being 04:
![image](https://user-images.githubusercontent.com/33301226/145102759-c313ab7b-3154-4438-899f-7c212fc34003.png)

That also generates a bad disassembly:
![image](https://user-images.githubusercontent.com/33301226/145102838-5919717e-7101-4f03-86a3-e15e11c455b4.png)

**Comment by yetmorecode** [comment]
I wasn't sure about those. These are 16:16 pointer fixups, i.e. those far jumps are of the format <16bit segment selector>:<16 bit offset into segment>. Supposedly they are meant to go into object#4, offset 4, which equates to 0x150004. Unfortunately Ghidra has no notion of 32 bit protected mode segment selectors (only for 16bit realmode code), so there is no way to patch the "jmpf" directly.

```
[Object#2] Mapping to memory location 00020000 - 0013de1c (selector 001)
16:16 pointer fixup #0 at 00135eee (page 116) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #1 at 00135f2f (page 116) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #2 at 00135f83 (page 116) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #3 at 0013600f (page 117) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #4 at 0013608f (page 117) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #5 at 00136139 (page 117) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #6 at 0013619c (page 117) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
16:16 pointer fixup #7 at 001361f4 (page 117) -> 150000:0004 (object #4, target flags:  0  16-bit target offset, 8-bit object number,)
```

On the other hand for analysis I think it's probably ok to patch the far jmp with a normal jmp.

**Comment by enderdrag64** [comment]
@yetmorecode Oh that makes sense. 

> Unfortunately Ghidra has no notion of 32 bit protected mode segment selectors (only for 16bit realmode code), so there is no way to patch the "jmpf" directly.

Is the reason for that because Ghidra wasn't ever designed to handle 32-bit DOS extenders?

> On the other hand for analysis I think it's probably ok to patch the far jmp with a normal jmp.

So if I manually replace the jmpf call with a jmp and then set the address to 0x150004, it should match the behavior of the executable for analysis purposes?

**Comment by yetmorecode** [comment]
Ok, so I dug further down this rabbit hole to get an understanding of how it all works. Long story short: pretty much as I thought. However lets write my learnings for future reference.

So I start my dosbox debugger with DOS32A  in verbose mode (```SET DOS32A=/VERBOSE:1" in dosbox.conf).

![image](https://user-images.githubusercontent.com/11893375/145903818-a43111d7-fd20-441c-b261-f09f987bc30a.png)

The base addresses and segment selectors can be synced with Ghidra:

![image](https://user-images.githubusercontent.com/11893375/145903939-0427ec42-c9f2-4569-93c8-fa5def80beba.png)

I added support to the loader to mark fixups with labels & comments, so it's easier to find them:

![image](https://user-images.githubusercontent.com/11893375/145906143-d0394396-d937-42ef-ba1f-2814118a4cf6.png)

In the loader options, you can also choose to not apply certain fixups. Here is one of those JMPF unfixed and its all its glory:

![image](https://user-images.githubusercontent.com/11893375/145906255-9bdf185a-cfa3-433a-ac3e-67ff83062cde.png)

And here the fixup record for it saying the target is object #4 + offset 0x4:

![image](https://user-images.githubusercontent.com/11893375/145910693-9a253af4-beba-491d-ae0b-4b040a38971a.png)

Comapred with dosbox, that seems quite accurate (given the real segment selector is 828 for object #4 and base address has changed as well):

![image](https://user-images.githubusercontent.com/11893375/145911112-e6858bd2-2511-4474-a4b0-900d54f6e402.png)

The disassembler however seems to mishandle to 66h prefixed JMPF, reading two bytes too much (https://onlinedisassembler.com/odaweb/PkiI8CBw/0).

The actual operand order of the JMPF is "ea" <16-bit offset> <16-bit selector>, so "ea 04 00 28 08" looks quite right.

I tried overwriting the operand for those 1616 pointer fixups, and it seems to work quite well so far:

![image](https://user-images.githubusercontent.com/11893375/145912000-fa687432-ed0c-4d36-bd92-ff69642e6d0c.png)

Unless there are more issues in RGFX.exe, I will probably close the ticket soon.

**Comment by yetmorecode** [comment]
@enderdrag64 I overwrite those JMPF with calculated jumps and it looks quite decent. Hope that  helps

![image](https://user-images.githubusercontent.com/11893375/145912176-72074338-d6f4-4ed7-939e-0884d9bf2274.png)
