### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by bluddy** [yetmorecode/ghidra-lx-loader#2]
I'm new at ghidra but have been using IDA Free for a while.

I'd like to disassemble and analyze a DOS4GW-based game. After installing this extension and opening the executable, I expect to see the starting real-mode segments, and then the protected mode 32-bit segments for the rest of the code. I'm not sure this is actually happening. Is there anything specific I need to do?

**Comment by yetmorecode** [comment]
If the installation went correct, it should detect LX/LE/LC when importing a new file:
![image](https://user-images.githubusercontent.com/11893375/163415640-bec33178-3303-4823-83af-5933d785a87c.png)

And when you then import it, it should look like this:
![image](https://user-images.githubusercontent.com/11893375/163415849-96450bb6-6378-4175-acc9-1ab3e66e5eb9.png)

Which ghidra version did you download? I might have to push an update for 10.1 as the latest release is for 10.0 still.

**Comment by yetmorecode** [comment]
You will not see the MZ 16-bit code, as Ghidra does not support mixed memory models to map both the 32 bit and the 16 bit code at the same time. However, for dos4gw games the MZ loader is pretty standard stuff and not of much interest anyway I'd say. So you won't need it unless you feel like reversing a particular DOS extender itself.

**Comment by bluddy** [comment]
I have the latest ghidra 10.1.2. I just updated the version string in your loader to make it work lol.
Yeah I don't care about the MZ loader. I'll give it another shot and see if it works.

Also another question: I've been working for a while on a different project for an older MZ executable that's entirely 16 bit. It has 20 different possible overlays into the last part of the main segment, and loads them into that area as necessary when reaching the particular part of the game. I had to work around IDA Free's limitations to support it (I just saved the memory image from dosbox, and then loaded it into IDA, which allows working with DOS files). I also have 20 different versions of the IDA file, to deal with the different overlay possibilities. Would your loader have a better way of dealing with this issue? IDA wants to put the overlays in different segments, which doesn't work because they all assume the same memory location and access data and code that's previous to them in the segment.

**Comment by yetmorecode** [comment]
> I have the latest ghidra 10.1.2. I just updated the version string in your loader to make it work lol. Yeah I don't care about the MZ loader. I'll give it another shot and see if it works.

Alright haha.

> Also another question: I've been working for a while on a different project for an older MZ executable that's entirely 16 bit. It has 20 different possible overlays into the last part of the main segment, and loads them into that area as necessary when reaching the particular part of the game. I had to work around IDA Free's limitations to support it (I just saved the memory image from dosbox, and then loaded it into IDA, which allows working with DOS files). I also have 20 different versions of the IDA file, to deal with the different overlay possibilities. Would your loader have a better way of dealing with this issue? IDA wants to put the overlays in different segments, which doesn't work because they all assume the same memory location and access data and code that's previous to them in the segment.

No, this loader won't load any 16 bit code from the original MZ at all. Everything needed for LE executables is outside the MZ part, even if they are mixed 16/32 bit, the 16bit code will be put into an LE-style object. Your only option there is to use the standard MZ loader from ghidra, which I can't tell how good it is.

Writing a custom loader however is pretty easy. I'm sure you could put something tailored to your needs together in no time.

**Comment by bluddy** [comment]
OK just tried it and the extension is not activated. I don't get the option to load an LE/LX file when I import it. Any idea how to update it?

**Comment by bluddy** [comment]
I installed ghidra 10.0.1, installed the extension, and the file type is still not detected by the loader...

**Comment by yetmorecode** [comment]
Can I find the file somewhere to test it? 

I also updated the release page. There was a release for 10.1 from december but somehow it wasn't showing up as latest.

**Comment by bluddy** [comment]
It's either of the 2 executables used for x-com apocalypse.

**Comment by yetmorecode** [comment]
The xcomapoc.exe from the GOG version is not an LE exe and doesn't use a DOS extender. It's just a plain old MZ exe, so I guess Ghidra is right saying its Old-Style MZ.

**Comment by bluddy** [comment]
That's just a wrapper. You have to look deeper in the directories. You want the files TACP.exe and UFO2P.exe.

**Comment by yetmorecode** [comment]
I'm sorry to say, but neither TACP.exe nor UFO2P.exe look like Linear Executables either.

If you tried to parse them as LE, it just doesn't make sense. I don't think those MZ have a e_lfanew field at all. You can see on the right side that actual header seems to end after the overlay field and the reserved fields and lfanew are already from relocation data, which seems very wrong.

If you still ignored this red flag and continued, you would get a file layout as shown on the left, which clearly looks broken as well:

![image](https://user-images.githubusercontent.com/11893375/163708093-6b01ea54-67e5-4574-9432-dc7e83f734c1.png)

wdump.exe also seems to agree it's not LE.

`Open Watcom Executable Image Dump Utility Version 2.0 beta Jun  1 2021 00:37:25 (16-bit)
Copyright (c) 2002-2021 The Open Watcom Contributors. All Rights Reserved.
Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.

                                DOS EXE Header                                
==============================================================================
length of load module mod 200H                       =     0074H
number of 200H pages in load module                  =     007BH
number of relocation items                           =     004EH
size of header in paragraphs                         =     0020H
minimum number of paragraphs required above load mod =     0001H
maximum number of paragraphs required above load mod =     FFFFH
offset of stack segment in load module               =     0121H
initial value of SP                                  =     0340H
checksum                                             =     F7CDH
initial value of IP                                  =     2382H
offset of code segment within load module (segment)  =     01BDH
file offset of first relocation item                 =     001EH
overlay number                                       =     0000H
load module length                                   = 0000F474H

Additional file data follows DOS executable.

                           DOS/16M EXE Header - BW                            
==============================================================================
file offset = 0000F474H

                              DOS/16M EXE Header                              
==============================================================================
length of load module mod 200H                       =     0050H
number of 200H pages in load module                  =     0076H
reserved1                                            =     0000H
reserved2                                            =     0000H
minimum memory allocation in KB                      =     0001H
maximum memory allocation in KB                      =     0180H
initial value of SS                                  =     0090H
initial value of SP                                  =     78D0H
selector for start of huge reloc list                =     0098H
initial value of IP                                  =     88B3H
initial value of CS                                  =     0080H
runtime GDT size in bytes less one                   =     3FFFH
MAKEPM/GLU version * 100                             =     0818H
offset of possible next spliced .exp                 = 0001E0C4H
offset of debug info                                 = 0000EC50H
last selector value used                             =     0098H
private memory allocation in KB                      =     0000H
allocation increment (ExtReserve) in KB              =     0100H
reserved3                                            = 00000055H
reserved4                                            =     0000H
runtime options bit mask                             =     3010H
selector of transparent stack                        =     0000H
module flags                                         =     0007H
program size in paras                                =     0000H
file size of GDT in bytes less one                   =     009FH
first user selector (0 -> default of 0x80)           =     0080H
default mem strategy                                 =       00H
reserved5                                            =       92H
transfer buffer size in bytes (0 -> default of 8192) =     0000H
load module length                                   = 00000000H
GLU version                                          = 2. 72
original name: VMM.EXP

GDT selectors:
                                 Size in    Size in
Sel #    Access    File offset   File       Memory     DPL    Present    Flags
-----    ------    -----------   -------    -------    ---    -------    -----
0080      ER         00F544       0CA90      0CA90     0         1       
0088      RW         01BFD4       00000      00000     0         1       Z
0090      RW         01BFD4       01E90      08870     0         1       
0098      RW         01DE64       00260      00260     0         1       

                           DOS/16M EXE Header - BW                            
==============================================================================
file offset = 0001E0C4H

                              DOS/16M EXE Header                              
==============================================================================
length of load module mod 200H                       =     01E0H
number of 200H pages in load module                  =     00B8H
reserved1                                            =     0000H
reserved2                                            =     0000H
minimum memory allocation in KB                      =     0000H
maximum memory allocation in KB                      =     0000H
initial value of SS                                  =     00A8H
initial value of SP                                  =     7260H
selector for start of huge reloc list                =     00B0H
initial value of IP                                  =     2CD3H
initial value of CS                                  =     0080H
runtime GDT size in bytes less one                   =     FFFFH
MAKEPM/GLU version * 100                             =     0818H
offset of possible next spliced .exp                 = 000352A4H
offset of debug info                                 = 000171E0H
last selector value used                             =     00B0H
private memory allocation in KB                      =     0000H
allocation increment (ExtReserve) in KB              =     0000H
reserved3                                            = 0000006AH
reserved4                                            =     0000H
runtime options bit mask                             =     1000H
selector of transparent stack                        =     0000H
module flags                                         =     0005H
program size in paras                                =     0000H
file size of GDT in bytes less one                   =     00BFH
first user selector (0 -> default of 0x80)           =     0080H
default mem strategy                                 =       00H
reserved5                                            =       92H
transfer buffer size in bytes (0 -> default of 8192) =     0000H
load module length                                   = 00000000H
GLU version                                          = 2. 72
original name: 4GWPRO.EXP

GDT selectors:
                                 Size in    Size in
Sel #    Access    File offset   File       Memory     DPL    Present    Flags
-----    ------    -----------   -------    -------    ---    -------    -----
0080      ER         01E1B4       05F90      05F90     0         1       
0088      ER         024144       0C1C0      0C1C0     0         1       
0090      ER         030304       00740      00740     0         1       
0098      ER         030A44       00130      00130     0         1       
00A0      RW         030B74       00000      00030     0         1       Z
00A8      RW         030B74       040B0      07D00     0         1       
00B0      RW         034C24       00680      00680     0         1       

`

**Comment by bluddy** [comment]
Interesting. That's definitely a surprise to me.

**Comment by bluddy** [comment]
Everything I find online suggests the game uses DOS4GW. Doesn't that imply it uses linear executables?

**Comment by bluddy** [comment]
Also I was able to unpack the executable using the DOS32A unpacker. It's definitely an LE file.

**Comment by yetmorecode** [comment]
Indeed, I can see it now. Weird but certainly interesting. I should be able to make the loader load the unbound LE exe first for s start, than try figuring what's going on in the MZ part with SB.

**Comment by yetmorecode** [comment]
Ok I added support to load unbound LEs and it looks good to me now with the *.LE from sb.exe

https://github.com/yetmorecode/ghidra-lx-loader/releases/tag/v10.1-3

**Comment by bluddy** [comment]
It works! Thank you! Now I just need to learn ghidra :)

**Comment by yetmorecode** [comment]
@bluddy for the record, the original exe is in DOS/16M format http://www.rdos.net/svn/tags/V9.2.5/watcom/bld/wl/test/dos16m/readme.txt

**Comment by yetmorecode** [comment]
For what its worth, the next version will be able to load those files with all file headers out of the box (i.e. wihtout unbinding with sb.exe)

![image](https://user-images.githubusercontent.com/11893375/164569778-4920b26a-cb14-413d-93e5-a4c68132694c.png)
